## Calculating the PIT metric/histogram

## For each week in each season, the file records the predictions for all weeks, as well as the true value for all weeks.

## Note that in the current calculation we must have results for all weeks, not just a subset.

loc<-"San Juan"
## these files will be generated by first running sanjuan_glm.R or
## iquitos_glm.R across all seasons and then running combine_outs.R to
## aggregate the results.

if(loc=="San Juan") load("glm_dengue_sanjuan_testing_final.RData") 
if(loc=="Iquitos") load("glm_dengue_iquitos_testing_final.RData")

samps<-NULL
for(i in 1:104){
    out<-out.obj[[i]]
    for(j in 1:length(out$ytrue)){
        FN<-ecdf(out$tc[,j])
        samps<-c(samps, FN(out$ytrue[j]))
    }	    
}


samps.pi<-samps.pw<-samps.ti<-NULL
for(i in 1:104){
    out<-out.obj[[i]]
    pw.true<-which.max(out$ytrue)[1]
    pi.true<-out$ytrue[pw.true]
    ti.true<-sum(out$ytrue)

    pws<-apply(out$tc, 1, which.max)
    pis<-apply(out$tc, 1, max)
    tis<-rowSums(out$tc)
    
    FN.pw<-ecdf(pws)
    samps.pw<-c(samps.pw, FN.pw(pw.true))

    FN.pi<-ecdf(pis)
    samps.pi<-c(samps.pi, FN.pi(pi.true))

    FN.ti<-ecdf(tis)
    samps.ti<-c(samps.ti, FN.ti(ti.true))

   
}

PITsamps<-list(pi=samps.pi, pw=samps.pw, ti=samps.ti)

if(loc=="San Juan"){
    save(PITsamps, file="glm_dengue_sanjuan_final_PIT.RData")

    ## output to sanjan file
    pdf("pit_sanjuan_glm.pdf", width=5, height=14)
    par(mfrow=c(3,1), mar=c(2,5,1,1))
    hist(PITsamps$pi, xlab="", ylab="peak incidence", cex.lab=2, main="", ylim=c(0,50))
    hist(PITsamps$pw, xlab="", ylab="peak week", cex.lab=2, main="", ylim=c(0,50))
    hist(PITsamps$ti, xlab="", ylab="total incidence", cex.lab=2, main="", ylim=c(0,50))
    dev.off()
}
if(loc=="Iquitos"){
    save(PITsamps, file="glm_dengue_iquitos_final_PIT.RData")
    
    ## output to iquitos file
    pdf("pit_iquitos_glm.pdf", width=5, height=14)
    par(mfrow=c(3,1), mar=c(2,5,1,1))
    hist(PITsamps$pi, xlab="", ylab="peak incidence", cex.lab=2, main="", ylim=c(0,60))
    hist(PITsamps$pw, xlab="", ylab="peak week", cex.lab=2, main="", ylim=c(0,60))
    hist(PITsamps$ti, xlab="", ylab="total incidence", cex.lab=2, main="", ylim=c(0,60))
    dev.off()
}

if(FALSE){
    pdf(paste("pit_sanjuan_glm.pdf"), width=5, height=14)
    par(mfrow=c(3,1), mar=c(3,4,1,1))
    hist(PITsamps$pi, ylab="peak incidence", xlab="", main="")
    hist(PITsamps$pw, ylab="peak week", xlab="", main="")
    hist(PITsamps$ti, ylab="total incidence", xlab="", main="")
    dev.off()
}


